Step 1: Import Libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Step 2: Load Dataset

In [11]:
from google.colab import files
uploaded = files.upload()

Saving Employee data.csv to Employee data (3).csv

Step 3: Display First 5 Rows

In [12]:
df.head()

,id,gender,bdate,educ,jobcat,salary,salbegin,jobtime,prevexp,minority
0,1.0,Male,1952-02-03,15,Manager,57000.0,27000.0,98.0,144.0,No
1,2.0,Male,1958-05-23,16,Clerical,40200.0,18750.0,98.0,36.0,No
2,3.0,Female,1929-07-26,12,Clerical,21450.0,12000.0,98.0,381.0,No
3,4.0,Female,1947-04-15,8,Clerical,21900.0,13200.0,98.0,190.0,No
4,5.0,Male,1955-02-09,15,Clerical,45000.0,21000.0,98.0,138.0,No

Step 4: Check Dataset Information

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        474 non-null    float64
 1   gender    474 non-null    object
 2   bdate     473 non-null    object
 3   educ      474 non-null    int64
 4   jobcat    474 non-null    object
 5   salary    474 non-null    float64
 6   salbegin  474 non-null    float64
 7   jobtime   474 non-null    float64
 8   prevexp   474 non-null    object
 9   minority  474 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 37.2+ KB

Step 5: Check Shape of Dataset

In [14]:
print("Rows and Columns:", df.shape)

Rows and Columns: (474, 10)

Step 6: Check Missing Values

In [15]:
df.isnull().sum()

id          0
gender      0
bdate       1
educ        0
jobcat      0
salary      0
salbegin    0
jobtime     0
prevexp     0
minority    0
dtype: int64

Step 7: Handle Missing Values

In [16]:
df['bdate'].fillna(df['bdate'].mode()[0], inplace=True)

/tmp/ipykernel_421/3251292987.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bdate'].fillna(df['bdate'].mode()[0], inplace=True)

In [17]:
df.isnull().sum()

id          0
gender      0
bdate       0
educ        0
jobcat      0
salary      0
salbegin    0
jobtime     0
prevexp     0
minority    0
dtype: int64

Step 8: Check Duplicate Records

In [18]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [20]:
df.drop_duplicates(inplace=True)

Step 9: Statistical Summary

In [21]:
df.describe()

               id        educ         salary      salbegin     jobtime
count  474.000000  474.000000     474.000000    474.000000  474.000000
mean   237.500000   13.491561   34419.567511  17016.086498   81.109705
std    136.976275    2.884846   17075.661465   7870.638154   10.060945
min      1.000000    8.000000   15750.000000   9000.000000   63.000000
25%    119.250000   12.000000   24000.000000  12487.500000   72.000000
50%    237.500000   12.000000   28875.000000  15000.000000   81.000000
75%    355.750000   15.000000   36937.500000  17490.000000   90.000000
max    474.000000   21.000000  135000.000000  79980.000000   98.000000

Step 10: Detect Outliers in Salary

In [22]:
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['salary'] < lower) | (df['salary'] > upper)]

print("Number of Outliers:", len(outliers))

Number of Outliers: 55

Step 11: Remove Salary Outliers

In [23]:
df = df[(df['salary'] >= lower) & (df['salary'] <= upper)]